name: Daily Financial News Bot

on:
  schedule:
    - cron: '0 11 * * *'  # 7 AM EST (11 AM UTC)
  workflow_dispatch:  # Allows manual testing

jobs:
  send-financial-news:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.3.0'
          
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libxml2-dev libcurl4-openssl-dev libssl-dev
          
    - name: Install R packages
      run: |
        R -e "install.packages(c('telegram.bot', 'xml2', 'httr', 'stringr', 'dplyr', 'lubridate', 'jsonlite', 'rvest', 'ggplot2', 'base64enc'), dependencies=TRUE)"
          
      - name: Run bot
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: Rscript financial_bot.R
