name: Enhanced Python Financial Bot

on:
  schedule:
    - cron: '0 11 * * *'  # 7 AM EST (11 AM UTC)
  workflow_dispatch:  # Manual testing

jobs:
  send-financial-news:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-dev
          
      - name: Install Python packages
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run Python bot
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python financial_bot.py
